// <auto-generated />
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("DAL.Models.UserConfiguration", b =>
                {
                    b.Property<long>("TelegramUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Budget")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExceptedProfit")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MinChanceToBuy")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("MinChangeToSell")
                        .HasColumnType("INTEGER");

                    b.HasKey("TelegramUserId");

                    b.ToTable("UserConfigurations");
                });
#pragma warning restore 612, 618
        }
    }
}
